### ISSUE TITLE
Epic: Refactor ETL pipelines for all data sources

### ISSUE THREAD

**Issue by mbertrand** [mitodl/mit-open#102]
# Description/Context
The following ETL pipelines need to be migrated to the `learning_resources` app and use the new `LearningResource` models:

- [x] [xPro](https://github.com/mitodl/mit-open/issues/23)
- [x] [MITx (EdX)](https://github.com/mitodl/mit-open/issues/127)
- [x] [MITx Online](https://github.com/mitodl/mit-open/issues/125)
- [x] [Micromasters](https://github.com/mitodl/mit-open/issues/143)
- [x] [OCW](https://github.com/mitodl/mit-open/issues/114)
- [x] [Open Learning Library](https://github.com/mitodl/mit-open/issues/126)
- [x] [Podcasts](https://github.com/mitodl/mit-open/issues/17)
- [x] [Prolearn API data](https://github.com/mitodl/mit-open/issues/151)

# Plan/Design
Use the existing `course_catalog` pipelines as a starting point, and adjust as necessary to conform to new models.

Keep issue #9 in mind when assigning platform and offered_by values.
