### ISSUE TITLE
Epic: Add all LearningResource objects to the search index

### ISSUE THREAD

**Issue by mbertrand** [mitodl/mit-open#107]
# Description/Context
The following should be added to the search index:
- [x] [Courses](https://github.com/mitodl/mit-open/issues/38)
- [x] [Programs](https://github.com/mitodl/mit-open/issues/38)
- [x] [Podcasts, Podcast Episodes](https://github.com/mitodl/mit-open/issues/105)
- [x] [LearningPaths](https://github.com/mitodl/mit-open/issues/106)
- [x] [Contentfiles](https://github.com/mitodl/mit-open/issues/142)

# Plan/Design
Design should be roughly similar to current implementation in open-discussions, but based on new LearningResource models
