### ISSUE TITLE
Epic: Implement new learning resource models

### ISSUE THREAD

**Issue by mbertrand** [mitodl/mit-open#4]
Implement models for the new data schema as described in docs below.  

#### Designs and Mockups
https://docs.google.com/document/d/1EsA4m8Ft7vMnCBDRa6f1R8YPnrp5v20j6zmwex_81CU/edit
https://github.com/mitodl/open-discussions/issues/3894
https://docs.google.com/document/d/1t4xn0SjehhA1C_W--oC3L7HHkrPLdGnlEZQ-_Vj4qwI/edit

#### Acceptance Criteria:

```[tasklist]
### Tasks
- [x] https://github.com/mitodl/mit-open/issues/11
- [ ] https://github.com/mitodl/mit-open/issues/12
- [ ] https://github.com/mitodl/mit-open/issues/13
- [ ] https://github.com/mitodl/mit-open/issues/14
```
