### ISSUE TITLE
MIT News & Events - Scraper and API

### ISSUE THREAD

**Issue by mbertrand** [mitodl/mit-open#611]
### User Story

MIT Open should provide API’s that return MIT news articles and/or events.  These news articles and events should be scraped from a variety of external sources, preferably RSS feeds if available, otherwise HTML web pages or JSON files.

#### Implementation
Scraping of news/events will be handled in a new `news_events` app within django.

#### Pipelines
Similar to learning resource ETL pipelines, pipeline functions will be written to process various sources of news and events.

The _feedparser_ library will be used to extract and transform RSS entries into `FeedItem` objects stored in the database.  

The _beautifulsoup_ library will be used to extract and transform news/events from HTML for sites that do not offer RSS feeds.

#### Models

**FeedSource**
item_type: CharField (“news”, “event”)
title: CharField
url: URLField
description: TextField
image: ForeignKey(FeedImage)

**FeedItem**
-- A specific news article or event scraped from a source
source: ForeignKey (to FeedSource)

-- common to RSS feed items, and likely relevant to HTML-parsed content too:
guid: CharField (unqiue, often the same as the url below)
title: CharField
url: URLField
description: TextField
summary: TextField
topics: ManyToManyField(FeedTopic)
image: ForeignKey(FeedImage)
item_date: DateTimeField: either date published (news) or event date (events)

**FeedNewsDetail**
feed_item: ForeignKey(FeedItem)
authors: ArrayField(CharField)
topics: ArrayField(CharField)

**FeedEventDetail**
feed_item: ForeignKey(FeedItem)
location: ArrayField(CharField)
audience: ArrayField(CharField)
event_type: ArrayField(CharField)

**FeedImage**
url: URLField
description: CharField
alt: CharField

#### Tasks
_get_<pipeline_name>_data_: a celery task that will run a particular news/events pipeline on a regular basis (every 3 hours?).  Will need as many tasks as there are pipelines.

#### API endpoints
/api/v1/news_events/
Return all `FeedItem` objects.  Filter by feed_type (“news”, “event”), feed source, date?  Sort by publish date, item_date?

/api/v1/news_events_sources/
Return all `FeedSource` objects from which news and items are extracted.  Filter by feed type (news, events).

#### Sources for news and events

- https://openlearning.mit.edu/events (events)
- https://medium.com/feed/open-learning (news)
- https://exec.mit.edu/s/blog (news)

#### Requirements
- [x] ETL functions for all sources
  - [x] https://openlearning.mit.edu/events (events)
  - [x] https://medium.com/feed/open-learning (news)
  - [x] https://exec.mit.edu/s/blog (news)
- [x] API to return feed sources and feed items, filterable by type
