### ISSUE TITLE
Implement user "Subscribe" to search

### ISSUE THREAD

**Issue by shanbady** [mitodl/mit-open#708]
**User Story**

As a user , I would like to get notified when there are new learning resources that I’m interested in. These can be courses in topics that like, from certain departments, etc.

From a UI perspective, the flow looks like the following:
1 - user enters search term and filters down the list using the controls in the side nav
2 - there is a "subscribe" button that the user can click to be notified when new items are added to the catalog that match their query

Linked overview document: https://docs.google.com/document/d/1q33BWb_ls1pQC3L--arZBfTz0AQYPNpAXQ4tggg2PLU/edit#heading=h.u4eedlvpkf10

```[tasklist]
### Tasks
- [ ] https://github.com/mitodl/mit-open/issues/709
- [ ] https://github.com/mitodl/mit-open/issues/724
- [ ] https://github.com/mitodl/mit-open/issues/726
- [ ] https://github.com/mitodl/mit-open/issues/755
- [ ] https://github.com/mitodl/mit-open/issues/783
- [ ] https://github.com/mitodl/mit-open/issues/847
- [ ] https://github.com/mitodl/mit-open/issues/848
```
